x-redash-service: &redash-service
  image: redash/redash:25.8.0
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "9000:5000"
    environment:
      REDASH_WEB_WORKERS: 1

  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server

  scheduled_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 1

  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 1

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  mathesar:
    image: mathesar/mathesar:0.9.0
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mathesar
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: